stages:
  - build
  - deploy

variables:
  AWS_REGION: us-east-1
  EKS_CLUSTER: magicfit-eks-dev
  ECR_BASE: "158975163788.dkr.ecr.us-east-1.amazonaws.com"

build-and-push:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - apk add --no-cache aws-cli
    - aws ecr get-login-password --region $AWS_REGION |
        docker login --username AWS --password-stdin $ECR_BASE
  script:
    - docker build -t $ECR_BASE/magicfit-backend:$CI_COMMIT_SHA ./magicfit-backend
    - docker push $ECR_BASE/magicfit-backend:$CI_COMMIT_SHA
    - docker build -t $ECR_BASE/magicfit-frontend:$CI_COMMIT_SHA ./magicfit-frontend
    - docker push $ECR_BASE/magicfit-frontend:$CI_COMMIT_SHA
    - docker build -t $ECR_BASE/magicfit-magicmirror:$CI_COMMIT_SHA ./MagicMirror
    - docker push $ECR_BASE/magicfit-magicmirror:$CI_COMMIT_SHA

deploy-eks:
  stage: deploy
  image: alpine:3.19
  before_script:
    - apk add --no-cache aws-cli curl
    - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
    - chmod +x kubectl && mv kubectl /usr/local/bin/
    - aws eks update-kubeconfig --name $EKS_CLUSTER --region $AWS_REGION
  script:
    # Substitution des images
    - sed -i "s|BACKEND_IMAGE|$ECR_BASE/magicfit-backend:$CI_COMMIT_SHA|g" k8s/backend.yaml
    - sed -i "s|FRONTEND_IMAGE|$ECR_BASE/magicfit-frontend:$CI_COMMIT_SHA|g" k8s/frontend.yaml
    - sed -i "s|MAGICMIRROR_IMAGE|$ECR_BASE/magicfit-magicmirror:$CI_COMMIT_SHA|g" k8s/magicmirror.yaml

    # Namespace (en premier)
    - kubectl apply -f k8s/namespace.yaml

    # Ressources kube-system (aws-auth)
    - kubectl apply -n kube-system -f k8s/aws-auth.yml

    # Ressources namespace magicfit
    - kubectl apply -n magicfit -f k8s/storageclass.yaml
    - kubectl apply -n magicfit -f k8s/configmap.yaml
    - kubectl apply -n magicfit -f k8s/01-external-secrets-sa.yaml
    - kubectl apply -n magicfit -f k8s/db.yaml
    - kubectl apply -n magicfit -f k8s/backend.yaml
    - kubectl apply -n magicfit -f k8s/backend-hpa.yaml
    - kubectl apply -n magicfit -f k8s/backend-ngnix-config.yaml
    - kubectl apply -n magicfit -f k8s/frontend.yaml
    - kubectl apply -n magicfit -f k8s/magicmirror.yaml
    - kubectl apply -n magicfit -f k8s/worker.yaml

    # Rollout
    - kubectl rollout status deployment -n magicfit --timeout=300s
