apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: magicfit
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::273220735056:role/magicfit-eso-secretsmanager
