apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: magicfit-secrets
  namespace: magicfit
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: magicfit-secrets
    creationPolicy: Owner
  data:
    - secretKey: APP_KEY
      remoteRef:
        key: magicfit/dev/app
        property: APP_KEY
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: magicfit/dev/db
        property: MYSQL_ROOT_PASSWORD
    - secretKey: MYSQL_PASSWORD
      remoteRef:
        key: magicfit/dev/db
        property: MYSQL_PASSWORD
