apiVersion: v1
kind: Service
metadata:
  name: magicfit-db
  namespace: magicfit
spec:
  type: ClusterIP
  selector:
    app: magicfit-db
  ports:
  - name: mysql
    port: 3306
    targetPort: 3306
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: magicfit-db
  namespace: magicfit
spec:
  serviceName: magicfit-db
  replicas: 1
  selector:
    matchLabels:
      app: magicfit-db
  template:
    metadata:
      labels:
        app: magicfit-db
    spec:
      containers:
      - name: mariadb
        image: mariadb:10.11
        ports:
        - containerPort: 3306
        env:
        - name: MARIADB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: magicfit-secrets
              key: DB_ROOT_PASSWORD
        - name: MARIADB_DATABASE
          valueFrom:
            configMapKeyRef:
              name: magicfit-config
              key: DB_DATABASE
        - name: MARIADB_USER
          valueFrom:
            configMapKeyRef:
              name: magicfit-config
              key: DB_USERNAME
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: magicfit-secrets
              key: DB_PASSWORD
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "400Mi"
            cpu: "300m"
        volumeMounts:
        - name: datadir
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: datadir
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
