apiVersion: v1
kind: Service
metadata:
  name: magicfit-frontend
  namespace: magicfit
spec:
  type: LoadBalancer
  selector:
    app: magicfit-frontend
  ports:
  - name: http
    port: 80
    targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: magicfit-frontend
  namespace: magicfit
spec:
  replicas: 1        # ← réduit de 2 → 1 pour t3.micro
  selector:
    matchLabels:
      app: magicfit-frontend
  template:
    metadata:
      labels:
        app: magicfit-frontend
    spec:
      containers:
      - name: frontend
        image: 158975163788.dkr.ecr.us-east-1.amazonaws.com/magicfit-frontend:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "32Mi"
            cpu: "50m"
          limits:
            memory: "64Mi"
            cpu: "100m"
