apiVersion: v1
kind: ConfigMap
metadata:
  name: magicfit-magicmirror-proxy-conf
  namespace: magicfit
data:
  default.conf: |
    server {
        listen 80;

        location / {
            proxy_pass http://magicfit-magicmirror:8080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
