apiVersion: v1
kind: Secret
metadata:
  name: magicfit-secrets
  namespace: magicfit
type: Opaque
stringData:
  # DB/////////////////////////////////////
  MYSQL_PASSWORD: "y@ssine2018+-"
  MYSQL_ROOT_PASSWORD: "y@ssine2018+-"
  ###############################

  # Laravel
  APP_KEY: "base64:WnCOk2uBjMssX+tIN3V9ldJ8stYZVGrhDVFB/HFIMSQ="
