events {}

http {
  include       /etc/nginx/mime.types;
  default_type  application/octet-stream;

  server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    # Support Angular routing (fallback sur index.html)
    location / {
      try_files $uri $uri/ /index.html;
    }
  }
}
