name: magicfit-dev

on:
  push:
    branches: ["main"]

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
  EKS_CLUSTER_NAME: ${{ vars.EKS_CLUSTER_NAME }}


jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mariadb:10.11
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testing
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql, bcmath, gd, zip
      - name: Install Dependencies
        working-directory: ./magicfit-backend
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
      - name: Setup environment
        working-directory: ./magicfit-backend
        run: |
          cp .env.example .env
          php artisan key:generate
      - name: Run Tests
        working-directory: ./magicfit-backend
        env:
          DB_CONNECTION: mysql
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_DATABASE: testing
          DB_USERNAME: root
          DB_PASSWORD: root
        run: php artisan test

  build_push:
    runs-on: ubuntu-latest
    needs: [test]
    outputs:
      image_tag: ${{ steps.meta.outputs.image_tag }}
    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: meta
        run: echo "image_tag=sha-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        run: |
          aws ecr get-login-password --region $AWS_REGION \
          | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

      - name: Build & push backend
        run: |
          TAG=${{ steps.meta.outputs.image_tag }}
          docker build -t magicfit-backend:$TAG ./magicfit-backend
          docker tag magicfit-backend:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/magicfit-backend:$TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/magicfit-backend:$TAG

      - name: Build & push frontend
        run: |
          TAG=${{ steps.meta.outputs.image_tag }}
          docker build -t magicfit-frontend:$TAG ./magicfit-frontend
          docker tag magicfit-frontend:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/magicfit-frontend:$TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/magicfit-frontend:$TAG

      - name: Build & push magicmirror
        run: |
          TAG=${{ steps.meta.outputs.image_tag }}
          docker build -t magicfit-magicmirror:$TAG ./MagicMirror
          docker tag magicfit-magicmirror:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/magicfit-magicmirror:$TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/magicfit-magicmirror:$TAG

      - name: Build & push magicmirror-proxy
        run: |
          TAG=${{ steps.meta.outputs.image_tag }}
          docker build -t magicfit-magicmirror-proxy:$TAG -f ./Dockerfile.magicmirror-proxy .
          docker tag magicfit-magicmirror-proxy:$TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/magicfit-magicmirror-proxy:$TAG
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/magicfit-magicmirror-proxy:$TAG

  deploy:
    runs-on: ubuntu-latest
    needs: [build_push]
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::273220735056:role/magicfit-gha-deploy
          aws-region: ${{ env.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: kubeconfig
        run: aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME

      - name: Deploy (inject image tags)
        run: |
          TAG=${{ needs.build_push.outputs.image_tag }}

          kubectl apply -f k8s/00-namespace.yaml

          # Applique config & secrets & DB
          kubectl apply -f k8s/01-configmap.yaml -n magicfit
          ###kubectl apply -f k8s/02-secret.yaml -n magicfit
          kubectl apply -f k8s/10-db.yaml -n magicfit
          kubectl apply -f k8s/20-backend-nginx-config.yaml -n magicfit

          # Apply workloads
          kubectl apply -f k8s/21-backend.yaml -n magicfit
          kubectl apply -f k8s/22-backend-hpa.yaml -n magicfit
          kubectl apply -f k8s/30-frontend.yaml -n magicfit
          kubectl apply -f k8s/40-magicmirror.yaml -n magicfit
          kubectl apply -f k8s/41-magicmirror-proxy.yaml -n magicfit

          # Patch images to the SHA tag (works with IMMUTABLE)
          kubectl set image deploy/magicfit-backend php-fpm=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/magicfit-backend:$TAG -n magicfit
          kubectl set image deploy/magicfit-frontend frontend=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/magicfit-frontend:$TAG -n magicfit
          kubectl set image deploy/magicfit-magicmirror magicmirror=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/magicfit-magicmirror:$TAG -n magicfit
          kubectl set image deploy/magicfit-magicmirror-proxy nginx=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/magicfit-magicmirror-proxy:$TAG -n magicfit

          # Wait rollouts
          kubectl rollout status deploy/magicfit-backend -n magicfit
          kubectl rollout status deploy/magicfit-frontend -n magicfit
